name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy to VPS
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Instalar dependências
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Rodar testes
        run: |
          pip install pytest httpx pytest-asyncio
          pytest app/

      - name: Deploy via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd /caminho/do/seu/projeto-na-vps
            git pull origin main
            source venv/bin/activate
            pip install -r requirements.txt
            alembic upgrade head
            pm2 restart pia-api || pm2 start uvicorn --name pia-api -- app.main:app --host 0.0.0.0 --port 8000
